############
# Settings #
############
image: docker:24.0.6
services:
  - docker:24.0.6-dind
stages:
  - template
  - run
variables:
  BASE_TAG: "develop"
  USE_PRIVATE_IMAGES: 0
  KASM_RELEASE: "1.14.0"
  TEST_INSTALLER: "https://kasm-static-content.s3.amazonaws.com/kasm_release_1.14.0.7f3582.tar.gz"
before_script:
  - export SANITIZED_BRANCH="$(echo $CI_COMMIT_REF_NAME | sed -r 's#^release/##' | sed 's/\//_/g')"

#######################
# Build from template #
#######################
template:
  stage: template
  script:
    - apk add py3-jinja2 py3-yaml
    - cd ci-scripts
    - python3 template-gitlab.py
  tags:
    - oci-fixed-amd
  artifacts:
    paths:
      - gitlab-ci.yml
pipeline:
  stage: run
  except:
    variables:
      - $README_USERNAME_RUN
      - $README_PASSWORD_RUN
      - $DOCKERHUB_REVERT_RUN
      - $REVERT_IS_ROLLING_RUN
  trigger:
    include:
      - artifact: gitlab-ci.yml
        job: template
pipeline_readme:
  stage: run
  only:
    variables:
      - $README_USERNAME_RUN
      - $README_PASSWORD_RUN
  variables:
      README_USERNAME: $README_USERNAME_RUN
      README_PASSWORD: $README_PASSWORD_RUN
  trigger:
    include:
      - artifact: gitlab-ci.yml
        job: template
pipeline_revert:
  stage: run
  only:
    variables:
      - $DOCKERHUB_REVERT_RUN
      - $REVERT_IS_ROLLING_RUN
  variables:
      DOCKERHUB_REVERT: $DOCKERHUB_REVERT_RUN
      REVERT_IS_ROLLING: $REVERT_IS_ROLLING_RUN
  trigger:
    include:
      - artifact: gitlab-ci.yml
        job: template
